// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CheckObjectIds

int width;
int height;

RWStructuredBuffer<int> objectIds;
Texture2D<float4> pixelsTexture;

[numthreads(16,16,1)]
void CheckObjectIds (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= (uint)width || id.y >= (uint)height) return;
    float pixelId = pixelsTexture[id.xy].x;
    if(pixelId > 0) {
        objectIds[(int)pixelId] = 1;
    }
}
